import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KoulBelNthif",
  description: "Generated by Bassem",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-amber-500 w-full">{children}</body>
      </html>
    </ClerkProvider>
  );
}
